[versions]
lombok = "1.18.30"
jetbrains-annotations = "24.1.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
